### ISSUE TITLE
Adapter start module failures 

### ISSUE THREAD

**Issue by pacman13** [TA2k/ioBroker.parcel#16]
Hello,

after the installation (I tried it over GITHUB directly as recommended and over the repository) and right after the start I receive always the following error messages (attached). 

I also tried locally the recommended Npm commands:
 _"Rebuild for adapter system.adapter.parcel.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually."._

Software level i use:
Node.js    v14.19.1
NPM    6.14.16

Error log:

2022-03-26 07:03:08.212  - error: host.raspberrypi Caught by controller[0]: internal/modules/cjs/loader.js:1144
--
2022-03-26 07:03:08.213  - error: host.raspberrypi Caught by controller[0]:   return process.dlopen(module, path.toNamespacedPath(filename));
2022-03-26 07:03:08.213  - error: host.raspberrypi Caught by controller[0]:                  ^
2022-03-26 07:03:08.213  - error: host.raspberrypi Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
2022-03-26 07:03:08.214  - error: host.raspberrypi Caught by controller[0]: was compiled against a different Node.js version using
2022-03-26 07:03:08.214  - error: host.raspberrypi Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
2022-03-26 07:03:08.214  - error: host.raspberrypi Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
2022-03-26 07:03:08.215  - error: host.raspberrypi Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
2022-03-26 07:03:08.215  - error: host.raspberrypi Caught by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
2022-03-26 07:03:08.215  - error: host.raspberrypi Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-03-26 07:03:08.215  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-03-26 07:03:08.216  - error: host.raspberrypi Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2022-03-26 07:03:08.216  - error: host.raspberrypi Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:101:18)
2022-03-26 07:03:08.216  - error: host.raspberrypi Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
2022-03-26 07:03:08.216  - error: host.raspberrypi Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-03-26 07:03:08.216  - error: host.raspberrypi Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-03-26 07:03:08.217  - error: host.raspberrypi Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-03-26 07:03:08.217  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
2022-03-26 07:03:08.217  - error: host.raspberrypi Caught by controller[0]:   code: 'ERR_DLOPEN_FAILED'
2022-03-26 07:03:08.217  - error: host.raspberrypi Caught by controller[0]: }
2022-03-26 07:03:08.218  - error: host.raspberrypi instance system.adapter.parcel.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Comment by TA2k** [comment]
/opt/iobroker/
npm install canvas

**Comment by pacman13** [comment]
Brillant thanks .. sorry was not aware that this was a prerequisite ... works !!!
